/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package model;


public abstract class BoardObject {
	private int x;
	private int y;
	private boolean center;

	public BoardObject(int i, int j) {
		this.x = i;
		this.y = j;
	}
	public int getX() {
		return x;
	}
	public int getY() {
		return y;
	}
	public void setX(int x) {
		this.x = x;
	}
	public void setY(int y) {
		this.y = y;
	}
	public boolean isCenter() {
		return center;

	}
	public void setCenter(boolean center) {
		this.center = center;

	}
	@Override
	public String toString() {
		return "BoardObject [x=" + x + ", y=" + y + ", center=" + center + "]";
	}


}