/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package model;


public abstract class BoardObject {
	private int x;
	private int y;
	private boolean center;
	public int getX() {
		return x;
	}
	public int getY() {
		return y;
	}
	public BoardObject setX(int x) {
		this.x = x;
		return this;
	}
	public BoardObject setY(int y) {
		this.y = y;
		return this;
	}
	public boolean isCenter() {
		return false;
	}
	public void setCenter(boolean center) {
		this.center = center;
		
	}
}