/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package model;

import java.util.List;


public class Necromobile extends Piece {
	public Necromobile(int i, int j, Player player) {
		super(i, j, player);
		//TODO Auto-generated constructor stub
	}
	public List<Move> getMoves() {
		return null;
	}
	public void captureEvent() {
	}
}