/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package model;

public class Tile extends BoardObject {
	private Piece piece;
	public Tile(int i, int j) {
		super(i, j);
	}
	public Piece getPiece() {
		return piece;
	}
	public Tile setPiece(Piece piece) {
		this.piece = piece;
		return this;
	}
	public Tile linkPiece(Piece _piece) {
		if (_piece != null) {
			_piece.unlinkTile();
			_piece.setTile(this);
		}

		unlinkPiece();
		setPiece(_piece);
		return this;
	}
	public Tile unlinkPiece() {
		if (getPiece() != null) {
			getPiece().setTile(null);
			setPiece(null);
		}
		return this;
	}
}