/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package model;

import java.util.ArrayList;
import java.util.Iterator;


public class Game {
	private int aiDepth;
	private ArrayList<Player> players = new ArrayList<>();
	private Board board;
	public int getAiDepth() {
		return aiDepth;
	}
	public ArrayList<Player> getPlayers() {
		return players;
	}
	public Board getBoard() {
		return board;
	}
	public Game setAiDepth(int aiDepth) {
		this.aiDepth = aiDepth;
		return this;
	}
	public Game setBoard(Board board) {
		this.board = board;
		return this;
	}
	public Game linkPlayers(Player _players) {
		if (_players != null) {
			getPlayers().add(_players);
		}
		return this;
	}
	public Game linkBoard(Board _board) {
		setBoard(_board);
		return this;
	}
	public Game unlinkPlayers(Player _players) {
		if (_players != null) {
			getPlayers().remove(_players);
		}
		return this;
	}
	public Game unlinkPlayers(Iterator<Player> it) {
		it.remove();
		return this;
	}
	public Game unlinkBoard() {
		setBoard(null);
		return this;
	}
}