/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package model;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;


public class Player implements Killable {
	private Set<Piece> pieces = new HashSet<>();
	public Set<Piece> getPieces() {
		return pieces;
	}
	public Player linkPieces(Piece _pieces) {
		if (_pieces != null) {
			_pieces.unlinkPlayer();
			_pieces.setPlayer(this);
			getPieces().add(_pieces);
		}
		return this;
	}
	public Player unlinkPieces(Piece _pieces) {
		if (_pieces != null) {
			_pieces.setPlayer(null);
			getPieces().remove(_pieces);
		}
		return this;
	}
	public Player unlinkPieces(Piece _pieces, Iterator<Piece> it) {
		if (_pieces != null) {
			_pieces.setPlayer(null);
			it.remove();
		}
		return this;
	}
	@Override
	public boolean isDead() {
		return false;
	}
}