package com.sample
 
import model.*
import java.util.List;
import java.util.ArrayList;
import java.lang.Math;
global Game game;
 
rule "Is BoardObject In Center"
	no-loop true
    when
        $boardObject : BoardObject( x == 4, y == 4)
    then
        System.out.println( $boardObject.getClass().getName() + " is in center" );
        System.out.println($boardObject);
        $boardObject.setCenter(true);
		update($boardObject);
		System.out.println($boardObject);      
end

rule "A Piece just got into center"
    when
        $piece : Chief( center == true)
    then
    
        System.out.println( "Chief is in center, rearrange player order" ); 
end


rule "Piece"
	
	when
		$chief : Piece(isDead()==false, player == game.getCurrentPlayer(), $x : x, $y : y)
	then
		$chief.getAvailableMoves().clear();
		MinMaxNode $newMove = new MinMaxNode();
		$newMove.setMove(new Move());
		$newMove.getMove().setTileFrom($x, $y);
		$newMove.getMove().setTileTo($x, $y+1);
		$newMove.getMove().setPiece($chief);
		$newMove.setPlayer($chief.getPlayer());
		$newMove.setParent(game.getRoot());
		game.getRoot().addChild($newMove);
		$chief.getAvailableMoves().add($newMove.getMove());
		insert($newMove);
		
		$newMove = new MinMaxNode();
		$newMove.setMove(new Move());
		$newMove.getMove().setTileFrom($x, $y);
		$newMove.getMove().setTileTo($x+1, $y);
		$newMove.getMove().setPiece($chief);
		$newMove.setPlayer($chief.getPlayer());
		$newMove.setParent(game.getRoot());
		game.getRoot().addChild($newMove);
		$chief.getAvailableMoves().add($newMove.getMove());
		insert($newMove);
		
		$newMove = new MinMaxNode();
		$newMove.setMove(new Move());
		$newMove.getMove().setTileFrom($x, $y);
		$newMove.getMove().setTileTo($x-1, $y);
		$newMove.getMove().setPiece($chief);
		$newMove.setPlayer($chief.getPlayer());
		$newMove.setParent(game.getRoot());
		game.getRoot().addChild($newMove);
		$chief.getAvailableMoves().add($newMove.getMove());
		insert($newMove);
		
		$newMove = new MinMaxNode();
		$newMove.setMove(new Move());
		$newMove.getMove().setTileFrom($x, $y);
		$newMove.getMove().setTileTo($x, $y-1);
		$newMove.getMove().setPiece($chief);
		$newMove.setPlayer($chief.getPlayer());
		$newMove.setParent(game.getRoot());
		game.getRoot().addChild($newMove);
		$chief.getAvailableMoves().add($newMove.getMove());
		insert($newMove);
		
		$newMove = new MinMaxNode();
		$newMove.setMove(new Move());
		$newMove.getMove().setTileFrom($x, $y);
		$newMove.getMove().setTileTo($x-1, $y-1);
		$newMove.getMove().setPiece($chief);
		$newMove.setPlayer($chief.getPlayer());
		$newMove.setParent(game.getRoot());
		game.getRoot().addChild($newMove);
		$chief.getAvailableMoves().add($newMove.getMove());
		insert($newMove);
		
		$newMove = new MinMaxNode();
		$newMove.setMove(new Move());
		$newMove.getMove().setTileFrom($x, $y);
		$newMove.getMove().setTileTo($x+1, $y-1);
		$newMove.getMove().setPiece($chief);
		$newMove.setPlayer($chief.getPlayer());
		$newMove.setParent(game.getRoot());
		game.getRoot().addChild($newMove);
		$chief.getAvailableMoves().add($newMove.getMove());
		insert($newMove);
		
		$newMove = new MinMaxNode();
		$newMove.setMove(new Move());
		$newMove.getMove().setTileFrom($x, $y);
		$newMove.getMove().setTileTo($x+1, $y+1);
		$newMove.getMove().setPiece($chief);
		$newMove.setPlayer($chief.getPlayer());
		$newMove.setParent(game.getRoot());
		game.getRoot().addChild($newMove);
		$chief.getAvailableMoves().add($newMove.getMove());
		insert($newMove);
		
		$newMove = new MinMaxNode();
		$newMove.setMove(new Move());
		$newMove.getMove().setTileFrom($x, $y);
		$newMove.getMove().setTileTo($x-1, $y+1);
		$newMove.getMove().setPiece($chief);
		$newMove.setPlayer($chief.getPlayer());
		$newMove.setParent(game.getRoot());
		game.getRoot().addChild($newMove);
		$chief.getAvailableMoves().add($newMove.getMove());
		insert($newMove);
end

rule "Move on kill"

	when 
		$newMove : MinMaxNode(getMove().movesOnKill == null)
	then
		Move $newMove2 = new Move();
		$newMove2.setPiece($newMove.getMove().getTileTo().getPiece());
		$newMove2.setTileFrom($newMove.getMove().getTileTo());
		$newMove.getMove().setMovesOnKill($newMove2);
		update($newMove);
end

rule "MinMaxNode prunning"
	salience 5
	when 
		$newMove: MinMaxNode(move.getTileTo() == null || (move.getTileTo().getPiece() != null 
		&& move.getTileTo().getPiece().getPlayer().equals(move.getPiece().getPlayer())))
	then
		$newMove.getMove().getPiece().getAvailableMoves().remove($newMove.getMove()); 
		delete($newMove);
		System.out.println($newMove);
		game.getRoot().getChildren().remove($newMove);
end


rule "MinMax Expanding"
	salience 4
	when 
		$newMove: MinMaxNode(getMove().movesOnKill == null, $x : move.piece.x, $y : move.piece.y, $x2 : move.tileTo.x, $y2 : move.tileTo.y)
	then 
		MinMaxNode $newMove2 = new MinMaxNode();
		$newMove2.setMove(new Move());
		$newMove2.getMove().setTileFrom($x, $y);
		
		int $x3 = $x2 - $x;
		if($x3 != 0){
			$x3 = $x3 / Math.abs($x3);
		}
		
		int $y3 = $y2 - $y;
		if($y3 != 0){
			$y3 = $y3 / Math.abs($y3);
		}
		
		if($newMove.getMove().getPiece().getClass() == Millitant.class){
			if($newMove.getMove().getPiece().getX() + 2 < $x2+$x3){
				return;
			} else if($newMove.getMove().getPiece().getX() - 2 > $x2+$x3){
				return;
			} else if($newMove.getMove().getPiece().getY() + 2 < $y2+$y3){
				return;
			} else if($newMove.getMove().getPiece().getY() - 2 > $y2+$y3){
				return;
			}
		}
		
		
		$newMove2.getMove().setTileTo($x2 + $x3, $y2 + $y3);
		$newMove2.getMove().setPiece($newMove.getMove().getPiece());
		$newMove2.setPlayer($newMove.getMove().getPiece().getPlayer());
		$newMove2.setParent(game.getRoot());
		game.getRoot().addChild($newMove2);
		$newMove.getMove().getPiece().getAvailableMoves().add($newMove2.getMove());
		insert($newMove2);
end

rule "Heuristics"
	salience 3
	when
		$newMove : MinMaxNode()
		$numberOfSurvivors : Integer() from accumulate(
			Player($dead : isDead()),
			init(int survivors = 0;
				$newMove.getMove().execute();
			),
			action(if(!$dead) survivors++;),
			reverse(if(!$dead) survivors--;),
			result(survivors)
		)
		$nodeValues : ArrayList() from accumulate(
			$player : Player($dead : isDead()),
			
			init(
			
			ArrayList<Integer> values = new ArrayList<Integer>();
			values.add(0);
			values.add(0);
			values.add(0);
			values.add(0);
			
			Player lordPlayer = game.getLordPlayer();
			),
			
			action(
			if(!$dead && lordPlayer == null) values.set($player.getIndex(), 48/$numberOfSurvivors);
			else if(!$dead && lordPlayer == $player) values.set($player.getIndex(), 48);
			else values.set($player.getIndex(), 0);
			
			),
			reverse(if(!$dead) values.set($player.getIndex(), 0);),
			result(values)
		)
		
		$pieceValues : ArrayList() from accumulate(
			$piece : Piece($dead : isDead()),
			init(ArrayList<Integer> values = $nodeValues;),
			
			action(if(!$dead){
				if($piece.getClass() == Millitant.class){
					values.set($piece.getPlayer().getIndex(), values.get($piece.getPlayer().getIndex()) + 6);
				} else if($piece.getClass() == Necromobile.class){
					values.set($piece.getPlayer().getIndex(), values.get($piece.getPlayer().getIndex()) + 12);
				} else if($piece.getClass() == Assasin.class){
					values.set($piece.getPlayer().getIndex(), values.get($piece.getPlayer().getIndex()) + 18);
				} else if($piece.getClass() == Diplomat.class){
					values.set($piece.getPlayer().getIndex(), values.get($piece.getPlayer().getIndex()) + 12);
				} else if($piece.getClass() == Reporter.class){
					values.set($piece.getPlayer().getIndex(), values.get($piece.getPlayer().getIndex()) + 18);
				} else if($piece.getClass() == Chief.class){
					values.set($piece.getPlayer().getIndex(), values.get($piece.getPlayer().getIndex()) + 30);
				} 
			} else {
				for(Player p2 : game.getPlayers()){
					if(!$piece.getPlayer().equals(p2) && !p2.isDead()){
						if($piece.getPlayer().isDead()){
							if($piece.getClass() == Millitant.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (6/$numberOfSurvivors));
							} else if($piece.getClass() == Necromobile.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (12/$numberOfSurvivors));
							} else if($piece.getClass() == Assasin.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (18/$numberOfSurvivors));
							} else if($piece.getClass() == Diplomat.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (12/$numberOfSurvivors));
							} else if($piece.getClass() == Reporter.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (18/$numberOfSurvivors));
							} else if($piece.getClass() == Chief.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (30/$numberOfSurvivors));
							} 
						} else {
							if($piece.getClass() == Millitant.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (6));
							} else if($piece.getClass() == Necromobile.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (12));
							} else if($piece.getClass() == Assasin.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (18));
							} else if($piece.getClass() == Diplomat.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (12));
							} else if($piece.getClass() == Reporter.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (18));
							} else if($piece.getClass() == Chief.class){
								values.set(p2.getIndex(), values.get(p2.getIndex()) + (30));
							} 
						
						}
						
					}
				}
			
			}
			),
			
			result(values)
		)
		
		
	
	then
		$newMove.getMove().undo();
		

end




rule "Get Best Move"
	salience 2
	when
		$minMaxNode : MinMaxNode($parent: parent, $values: values, $player: player, $children : children)
	  	$bestChild : MinMaxNode() from accumulate(
	    $child: MinMaxNode( $valuesOfChild: values) from $children,        
	    init( MinMaxNode maxNode = null ),
	    action( 
	    if(maxNode == null) maxNode = $child;
	    if( $child.getValues().get($child.getPlayer().getIndex()) > maxNode.getValues().get(maxNode.getPlayer().getIndex()) ){
	                maxNode = $child;
	            } ),
	    result( maxNode ) )
	then
		$minMaxNode.setBestChild($bestChild);

end