/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root;

public class Move {
	private Move movesOnKill;
	private Piece piece;
	private Tile tile;
	public Move getMovesOnKill() {
		return movesOnKill;
	}
	public Piece getPiece() {
		return piece;
	}
	public Tile getTile() {
		return tile;
	}
	public Move setMovesOnKill(Move movesOnKill) {
		this.movesOnKill = movesOnKill;
		return this;
	}
	public Move setPiece(Piece piece) {
		this.piece = piece;
		return this;
	}
	public Move setTile(Tile tile) {
		this.tile = tile;
		return this;
	}
	public Move linkMovesOnKill(Move _movesOnKill) {
		setMovesOnKill(_movesOnKill);
		return this;
	}
	public Move linkPiece(Piece _piece) {
		setPiece(_piece);
		return this;
	}
	public Move linkTile(Tile _tile) {
		setTile(_tile);
		return this;
	}
	public Move unlinkMovesOnKill() {
		setMovesOnKill(null);
		return this;
	}
	public Move unlinkPiece() {
		setPiece(null);
		return this;
	}
	public Move unlinkTile() {
		setTile(null);
		return this;
	}
	public void execute() {
	}
	public void undo() {
	}
}